#ifndef __KINGDBENGINE_MODULES_AUDIO_AUDIOEXPORT_H__
#define __KINGDBENGINE_MODULES_AUDIO_AUDIOEXPORT_H__

enum ObjectType { AUDIO_LOADCOMPLETE, AUDIO_UNLOADCOMPLETE, AUDIO_ERROR };

#endif  // __KINGDBENGINE_MODULES_AUDIO_AUDIOEXPORT_H__